services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app

  app:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html:ro
    expose:
      - "80"

